/** Seeded dummy todos for initial state */
export const DUMMY_TODOS = [
  {
    id: "seed-001",
    text: "Complete the LevelUp onboarding walkthrough",
    completed: true,
    priority: "high",
    category: "Learning",
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "seed-002",
    text: "Read 20 pages of Atomic Habits",
    completed: true,
    priority: "high",
    category: "Learning",
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "seed-003",
    text: "Build the production Todo module",
    completed: false,
    priority: "high",
    category: "Dev",
    order: 2,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "seed-004",
    text: "Set up morning workout routine",
    completed: false,
    priority: "medium",
    category: "Health",
    order: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "seed-005",
    text: "Review Next.js 16 App Router docs",
    completed: false,
    priority: "medium",
    category: "Learning",
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seed-006",
    text: "Drink 3 liters of water",
    completed: false,
    priority: "low",
    category: "Health",
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "seed-007",
    text: "Design the LevelUp habit tracker wireframe",
    completed: false,
    priority: "medium",
    category: "Dev",
    order: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
